# Generated by Django 3.0.4 on 2020-11-01 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='categories',
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.Category'),
            preserve_default=False,
        ),
    ]
